export JAVA_HOME=`/usr/libexec/java_home -v 1.7`

# added by setup_fb4a.sh
export ANDROID_SDK=/Users/shuw/android-sdk-macosx
export ANDROID_NDK=/Users/shuw/android-ndk-r9b
export ANDROID_HOME=${ANDROID_SDK}
export PATH=${PATH}:${ANDROID_SDK}/tools:${ANDROID_SDK}/platform-tools

# added by setup_fb4a.sh
export ANDROID_SDK=/Users/shuw/android-sdk-macosx
export ANDROID_NDK=/Users/shuw/android-ndk-r9b
export ANDROID_HOME=${ANDROID_SDK}
export PATH=${PATH}:${ANDROID_SDK}/tools:${ANDROID_SDK}/platform-tools

# added by setup_fb4a.sh
export ANDROID_SDK=/Users/shuw/android-sdk-macosx
export ANDROID_NDK=/Users/shuw/android-ndk-r9b
export ANDROID_HOME=${ANDROID_SDK}
export PATH=${PATH}:${ANDROID_SDK}/tools:${ANDROID_SDK}/platform-tools

# added by setup_fb4a.sh
export ANDROID_SDK=/Users/shuw/android-sdk-macosx
export ANDROID_NDK=/Users/shuw/android-ndk-r9b
export ANDROID_HOME=${ANDROID_SDK}
export PATH=${PATH}:${ANDROID_SDK}/tools:${ANDROID_SDK}/platform-tools
