export JAVA_HOME=`/usr/libexec/java_home -v 1.7`

# added by setup_fb4a.sh
export ANDROID_SDK=/Users/shuw/android-sdk-macosx
export ANDROID_NDK_REPOSITORY=/Users/shuw/android-ndk
export ANDROID_HOME=${ANDROID_SDK}
export PATH=${PATH}:${ANDROID_SDK}/tools:${ANDROID_SDK}/platform-tools

alias build_graphql='~/fbandroid/java/com/facebook/graphql/build.sh'
alias sync_strings='DEVSERVER=dev199.prn2.facebook.com i18n/syncstrings --lib phone --config i18n/phone.config.json'
alias chrome_inspector="./scripts/open_inspector.sh -p com.facebook.phone"
alias avd="~/android-sdk-macosx/tools/android avd"

# BEGIN: Block added by chef, to set environment strings
# Please see https://fburl.com/AndroidProvisioning if you do not use bash
# or if you would rather this bit of code 'live' somewhere else
. ~/.fbchef/environment
# END: Block added by chef
