PS1='${debian_chroot:+($debian_chroot)}\u@\h:\W\$ '

export PATH=/usr/local/bin:$PATH
export PATH=~/bin:$PATH
export PATH=/usr/local/heroku/bin:$PATH
export PATH=/usr/local/share/npm/bin:$PATH
export JAVA_HOME=`/usr/libexec/java_home -v11`
export PATH="$JAVA_HOME/bin:$PATH"

 # Cargo is a Rust package maanger
source ~/.rbenv.sh
. "$HOME/.cargo/env"

# iTerm integration
test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"

alias httpserver='python -m SimpleHTTPServer &'
alias edit_alias="vim ~/profile/darwin/bashrc"
alias cgrep="grep --color=always"

eval "$(/opt/homebrew/bin/brew shellenv)"
